#!/bin/bash/
# author: nhd



############################

init_port=1111
samples=1

# For auto_analysis
date="2016-12-18"


#measurements=200000
measurements=20
normalizationWindowSize=40
smoothingWindowSize=100
outlierFactor=2
sdWindowSize=5
sdOutlierThreshold=500
# should be at least normalizationWindowSize x smoothingWindowSize x 2
steadyMeasurements=10000




#############################

path_project_code="/home/"$USER"/hiwi/repository/"

path_lab_machine="/home/"$USER"/hiwi/lab_machine/"
path_results_obs=$path_project_code"results/obs/"
path_results_cap=$path_project_code"results/capacity/"
path_results_plots=$path_project_code"results/plots/"

path_output=$path_project_code"output/"

