#!/bin/bash

source configuration

rm -R ./report/$date
mkdir ./report/$date
mkdir ./report/$date/plots
mkdir ./report/$date/plots/retTime
mkdir ./report/$date/plots/retTime_raw
mkdir ./report/$date/plots/other
mkdir ./report/$date/obs
mkdir ./report/$date/capacity

cp -R ./results/capacity/$date/sc_cc/* ./report/$date/capacity/


cp ./results/plots/$date/sc_cc/* ./report/$date/plots/
mv ./report/$date/plots/retTime[0-9].png ./report/$date/plots/retTime
mv ./report/$date/plots/retTime[0-9][0-9].png ./report/$date/plots/retTime
mv ./report/$date/plots/retTime*_raw.png ./report/$date/plots/retTime_raw
mv ./report/$date/plots/*.png ./report/$date/plots/other

cp ./report_muster ./report/$date/report.txt
cp ./configuration ./report/$date/

cp ./results/obs/$date/sc_cc/* ./report/$date/obs/
cp ./mean_and_err.py ./report/$date/obs/
cd ./report/$date/obs/
python mean_and_err.py
rm mean_and_err.py
mv report_retTime.dat ../

